[default.extend-words]
# keyword fp
"hel" = "hel"
# keep for comptability
"Sempahore" = "Sempahore"

[files]
extend-exclude = [
    "opcua/uamsg/std_nodeids_object.go",
    "opcua/uamsg/std_nodeids_variable.go",
    "go.mod",
    "go.sum",
]
